### ISSUE TITLE
Open source the actual production configuration

### ISSUE THREAD

**Issue by p-bizouard** [CentraleSupelec/aristote-dispatcher#11]
```yaml
models:
  - name: llama3 #must be lowercase
    model: "casperhansen/llama-3-70b-instruct-awq"
    servedModelName: ""
    quantization: "awq"
    dtype: ""
    gpuMemoryUtilization: "0.96"
    huggingface_token: ""
    ropeScaling:
      enabled: true
      jsonConfiguration: '{"type":"dynamic","factor":4.0}'
      theta: "500000"
    replicaCount: 1
    pvc:
      enabled: true
      storageSize: 60Gi

sender:
  image:
    tag: v1.1.1
consumer:
  image:
    tag: v1.1.1
inferenceserver:
  image:
    repository: vllm/vllm-openai
    tag: v0.5.0
```
